export const SYNC_CONNECT_STATUS = 'SYNC_CONNECT_STATUS';
export const SHOW_SNACK_BAR = 'SHOW_SNACK_BAR';
export const HIDE_SNACK_BAR = 'HIDE_SNACK_BAR';
export const SHOW_PROGRESS_BAR = 'SHOW_PROGRESS_BAR';
export const HIDE_PROGRESS_BAR = 'HIDE_PROGRESS_BAR';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
